Use EISOP dependencies
eisop/templatefora-checker pull request #1
Opened 2024-11-22 23:45 UTC by Ao-senXiong

I fork this repo from upperstream to have a template with EISOP CF.

Merge with https://github.com/eisop/checker-framework/pull/1048.

Merge after https://github.com/eisop/templatefora-checker/pull/2

2025-01-02 22:54 UTC, wmdietl requested changes
Thanks for forking and preparing this!
In a separate PR, can you add this repo as a downstream test for eisop/checker-framework?

2025-01-02 22:54 UTC, wmdietl commented on build.gradle
> +        eisopVersion: '3.42.0-eisop4',
```suggestion
        eisopVersion: '3.42.0-eisop5',
```

2025-01-02 22:54 UTC, wmdietl commented on src/main/java/org/checkerframework/checker/templatefora/qual/TemplateforaBottom.java
> -@TargetLocations({TypeUseLocation.EXPLICIT_LOWER_BOUND, TypeUseLocation.EXPLICIT_UPPER_BOUND})
Why remove this?

2025-01-02 22:57 UTC, wmdietl requested changes
README.md contains a few mentions of `org.checkerframework` that should be replaced by a checker-dependent organization.

2025-01-05 03:03 UTC, Ao-senXiong commented on src/main/java/org/checkerframework/checker/templatefora/qual/TemplateforaBottom.java
> -@TargetLocations({TypeUseLocation.EXPLICIT_LOWER_BOUND, TypeUseLocation.EXPLICIT_UPPER_BOUND})
The subtypingtest has a few usage of `@TemplateforaBottom int d = y;` which issues extra errors for eisop because we enforce target location. I think for this template checker, we can more lenient and let you to specify what kind of target location they want.

2025-01-05 21:04 UTC, wmdietl commented on src/main/java/org/checkerframework/checker/templatefora/qual/TemplateforaBottom.java
> -@TargetLocations({TypeUseLocation.EXPLICIT_LOWER_BOUND, TypeUseLocation.EXPLICIT_UPPER_BOUND})
I think the template should follow the recommended style. For a real checker, bottom should only be used in these locations. We can disable the `@TargetLocations` tests for the test cases and document why we do it there.

2025-01-05 21:10 UTC, wmdietl requested changes

2025-01-05 21:10 UTC, wmdietl commented on README.md
> +  `.checker.templatefora`) so that it reflects your
```suggestion
  `org.checkerframework.checker.templatefora`) so that it reflects your
```

2025-01-05 21:10 UTC, wmdietl commented on README.md
> +  `io.github.eisop.checker.templatefora` and
```suggestion
  `org.checkerframework.checker.templatefora` and
```

2025-01-05 21:10 UTC, wmdietl commented on README.md
> +    annotationProcessor 'io.github.eisop:templatefora-checker:0.1-SNAPSHOT'
This should use neither `org.checkerframework` nor `io.github.eisop`. This should use an organization from the user of the template.

2025-01-05 21:10 UTC, wmdietl commented on build.gradle
> +            groupId = 'io.github.eisop'
Like above, there should be a note here that this needs to be changed to something under the template users control.

2025-01-06 21:58 UTC, wmdietl reviewed
I'll merge this now, as eisop/cf master is failing, because https://github.com/eisop/checker-framework/pull/1048 sneakily already used this branch. So please open a new PR to further improve the template.

2025-01-06 21:58 UTC, wmdietl commented on src/main/java/org/checkerframework/checker/templatefora/qual/TemplateforaBottom.java
> -@TargetLocations({TypeUseLocation.EXPLICIT_LOWER_BOUND, TypeUseLocation.EXPLICIT_UPPER_BOUND})
Why did you resolve this? This comment wasn't addressed.

2025-01-06 21:59 UTC, merged

2025-01-06 22:22 UTC, Ao-senXiong commented
>Why did you resolve this? This comment wasn't addressed.

Oh, I did push my local commits but looks like it is not successful.